### ISSUE TITLE
使用viewbinding报错

### ISSUE THREAD

**Issue by yzgt** [junixapp/XPopup#1216]
**XPopup版本**
如2.2.0

**描述你的问题**
//ViewBinding
binding = XXXBinding.bind(getPopupImplView());

按照文档说的写法,报错了啊, 以下是代码截图和报错截图:

![image](https://github.com/junixapp/XPopup/assets/12458562/ce9d2565-3c39-4704-a0f3-1a72605a54eb)

![image](https://github.com/junixapp/XPopup/assets/12458562/f8b4cefd-5ae5-46b2-9b59-075a53d187a1)

**Comment by xiaqiuli** [comment]
getImplLayoutId()
